


export const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILURE = 'FETCH_TASK_FAILURE';
export const ADD_TASK_ITEM = 'ADD_TASK_ITEM';
export const DELETE_TASK_ITEM = 'DELETE_TASK_ITEM';
export const EDIT_TASK_ITEM = 'EDIT_TASK_ITEM';